### ISSUE TITLE
Benign NPE with tools.build uberjar

### ISSUE THREAD

**Issue by lispyclouds** [mpenet/hirundo#11]
This is an interesting issue. When building an AOT'ed uberjar with tools.build I see this seemingly benign NPE which doesn't seem to affect the operation:
```
Exception in thread "features-thread" java.lang.NullPointerException: Cannot invoke "java.util.Set.forEach(java.util.function.Consumer)" because the return value of "java.util.Map.get(Object)" is null
        at io.helidon.common.features.HelidonFeatures.features(HelidonFeatures.java:217)
        at io.helidon.common.features.HelidonFeatures.lambda$print$0(HelidonFeatures.java:92)
        at java.base/java.lang.Thread.run(Thread.java:1583)
```
Note: this **only happens when using the AOT uberjar from tools.build and NOT lein**

Steps to repro:
- deps.edn:
  ```edn
  {:paths ["src"]
   :deps {com.s-exp/mina {:mvn/version "0.1.23"}}
   :aliases {:build {:deps {io.github.clojure/tools.build {:git/tag "v0.9.6" :git/sha "8e78bcc"}}
                     :ns-default build}}}

  ```
- build.clj:
  ```clojure
  (ns build
    (:require [clojure.tools.build.api :as b]))
  
  (def uber-file "foo.jar")
  
  (defn clean
    [_]
    (b/delete {:path "target"})
    (b/delete {:path uber-file}))
  
  (defn uber
    [_]
    (let [basis (b/create-basis {:project "deps.edn"})
          class-dir "target/classes"
          src-dirs ["src"]]
      (clean nil)
      (b/write-pom {:class-dir class-dir
                    :lib 'bar/foo
                    :version "0.1.0"
                    :basis basis
                    :src-dirs src-dirs})
      (b/copy-dir {:src-dirs (conj src-dirs "resources")
                   :target-dir class-dir})
      (b/compile-clj {:basis basis
                      :src-dirs src-dirs
                      :class-dir class-dir
                      :ns-compile '[foo.main]
                      :java-cmd (or (System/getenv "JAVA_CMD") "java")
                      :java-opts ["--enable-preview"]
                      :compile-opts {:direct-linking true}})
      (b/uber {:class-dir class-dir
               :uber-file uber-file
               :basis basis
               :main 'foo.main})))

  ```
- src/foo/main.clj:
  ```clojure
  (ns foo.main
    (:require
     [s-exp.mina :as mina])
    (:gen-class))
  
  (defn -main
    [& _args]
    (mina/start! (fn [_req]
                   {:status 200
                    :body "Hello"})
                 {:port 8080
                  :host "0.0.0.0"}))

  ```
- build the uberjar: `clojure -T:build uber`
- Run the jar: `java -jar foo.jar` to see the NPE occur but things work as expected. Running without AOT with `clojure -M -m foo.main` doesn't seem to have this issue.

I'll try to dig into it and see if I can find where it's coming from, no idea as of now 😅

**Comment by mpenet** [comment]
Oh interesting. The stacktrace is odd. Thanks for the detailed report.

**Comment by mpenet** [comment]
Looking at it quickly I think it's likely an helidon bug
